//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceProducto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoProducto", Namespace="http://schemas.datacontract.org/2004/07/CapaServicioServidor")]
    public partial class DtoProducto : object
    {
        
        private string CodigoField;
        
        private double CostoField;
        
        private string DescripcionField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdProductoField;
        
        private double ImpuestoField;
        
        private double MargenGananciaField;
        
        private double NetoGravadoField;
        
        private ServiceProducto.Estado OEstadoField;
        
        private ServiceProducto.GeneroProducto OGeneroProductoField;
        
        private ServiceProducto.Marca OMarcaField;
        
        private ServiceProducto.RubroProducto ORubroProductoField;
        
        private double PrecioVentaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Costo
        {
            get
            {
                return this.CostoField;
            }
            set
            {
                this.CostoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto
        {
            get
            {
                return this.IdProductoField;
            }
            set
            {
                this.IdProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Impuesto
        {
            get
            {
                return this.ImpuestoField;
            }
            set
            {
                this.ImpuestoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MargenGanancia
        {
            get
            {
                return this.MargenGananciaField;
            }
            set
            {
                this.MargenGananciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NetoGravado
        {
            get
            {
                return this.NetoGravadoField;
            }
            set
            {
                this.NetoGravadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.GeneroProducto OGeneroProducto
        {
            get
            {
                return this.OGeneroProductoField;
            }
            set
            {
                this.OGeneroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Marca OMarca
        {
            get
            {
                return this.OMarcaField;
            }
            set
            {
                this.OMarcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.RubroProducto ORubroProducto
        {
            get
            {
                return this.ORubroProductoField;
            }
            set
            {
                this.ORubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioVenta
        {
            get
            {
                return this.PrecioVentaField;
            }
            set
            {
                this.PrecioVentaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Marca", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class Marca : object
    {
        
        private string DescripcionField;
        
        private int IdMarcaField;
        
        private ServiceProducto.Estado OEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMarca
        {
            get
            {
                return this.IdMarcaField;
            }
            set
            {
                this.IdMarcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RubroProducto", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class RubroProducto : object
    {
        
        private string DescripcionField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdRubroProductoField;
        
        private ServiceProducto.Estado OEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRubroProducto
        {
            get
            {
                return this.IdRubroProductoField;
            }
            set
            {
                this.IdRubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public enum Estado : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactivo = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneroProducto", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public enum GeneroProducto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unisex = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Masculino = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Femenino = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProducto.IServiceProducto")]
    public interface IServiceProducto
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/IngresarProducto", ReplyAction="http://tempuri.org/IServiceProducto/IngresarProductoResponse")]
        bool IngresarProducto(ServiceProducto.DtoProducto oProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/IngresarProducto", ReplyAction="http://tempuri.org/IServiceProducto/IngresarProductoResponse")]
        System.Threading.Tasks.Task<bool> IngresarProductoAsync(ServiceProducto.DtoProducto oProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ModificarProducto", ReplyAction="http://tempuri.org/IServiceProducto/ModificarProductoResponse")]
        bool ModificarProducto(ServiceProducto.DtoProducto oProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ModificarProducto", ReplyAction="http://tempuri.org/IServiceProducto/ModificarProductoResponse")]
        System.Threading.Tasks.Task<bool> ModificarProductoAsync(ServiceProducto.DtoProducto oProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/EliminarProducto", ReplyAction="http://tempuri.org/IServiceProducto/EliminarProductoResponse")]
        bool EliminarProducto(int IdProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/EliminarProducto", ReplyAction="http://tempuri.org/IServiceProducto/EliminarProductoResponse")]
        System.Threading.Tasks.Task<bool> EliminarProductoAsync(int IdProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ListaProducto", ReplyAction="http://tempuri.org/IServiceProducto/ListaProductoResponse")]
        System.Collections.Generic.List<ServiceProducto.DtoProducto> ListaProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ListaProducto", ReplyAction="http://tempuri.org/IServiceProducto/ListaProductoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceProducto.DtoProducto>> ListaProductoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerGeneroProducto", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerGeneroProductoResponse")]
        ServiceProducto.GeneroProducto ObtenerGeneroProducto(string oGeneroProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerGeneroProducto", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerGeneroProductoResponse")]
        System.Threading.Tasks.Task<ServiceProducto.GeneroProducto> ObtenerGeneroProductoAsync(string oGeneroProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerEstado", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerEstadoResponse")]
        ServiceProducto.Estado ObtenerEstado(string oEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerEstado", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerEstadoResponse")]
        System.Threading.Tasks.Task<ServiceProducto.Estado> ObtenerEstadoAsync(string oEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerRubroProducto", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerRubroProductoResponse")]
        ServiceProducto.RubroProducto ObtenerRubroProducto(string oRubroProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerRubroProducto", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerRubroProductoResponse")]
        System.Threading.Tasks.Task<ServiceProducto.RubroProducto> ObtenerRubroProductoAsync(string oRubroProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerMarca", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerMarcaResponse")]
        ServiceProducto.Marca ObtenerMarca(string oMarca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerMarca", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerMarcaResponse")]
        System.Threading.Tasks.Task<ServiceProducto.Marca> ObtenerMarcaAsync(string oMarca);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IServiceProductoChannel : ServiceProducto.IServiceProducto, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class ServiceProductoClient : System.ServiceModel.ClientBase<ServiceProducto.IServiceProducto>, ServiceProducto.IServiceProducto
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceProductoClient() : 
                base(ServiceProductoClient.GetDefaultBinding(), ServiceProductoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceProducto.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceProductoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceProductoClient.GetBindingForEndpoint(endpointConfiguration), ServiceProductoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceProductoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceProductoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceProductoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceProductoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool IngresarProducto(ServiceProducto.DtoProducto oProducto)
        {
            return base.Channel.IngresarProducto(oProducto);
        }
        
        public System.Threading.Tasks.Task<bool> IngresarProductoAsync(ServiceProducto.DtoProducto oProducto)
        {
            return base.Channel.IngresarProductoAsync(oProducto);
        }
        
        public bool ModificarProducto(ServiceProducto.DtoProducto oProducto)
        {
            return base.Channel.ModificarProducto(oProducto);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarProductoAsync(ServiceProducto.DtoProducto oProducto)
        {
            return base.Channel.ModificarProductoAsync(oProducto);
        }
        
        public bool EliminarProducto(int IdProducto)
        {
            return base.Channel.EliminarProducto(IdProducto);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProductoAsync(int IdProducto)
        {
            return base.Channel.EliminarProductoAsync(IdProducto);
        }
        
        public System.Collections.Generic.List<ServiceProducto.DtoProducto> ListaProducto()
        {
            return base.Channel.ListaProducto();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceProducto.DtoProducto>> ListaProductoAsync()
        {
            return base.Channel.ListaProductoAsync();
        }
        
        public ServiceProducto.GeneroProducto ObtenerGeneroProducto(string oGeneroProducto)
        {
            return base.Channel.ObtenerGeneroProducto(oGeneroProducto);
        }
        
        public System.Threading.Tasks.Task<ServiceProducto.GeneroProducto> ObtenerGeneroProductoAsync(string oGeneroProducto)
        {
            return base.Channel.ObtenerGeneroProductoAsync(oGeneroProducto);
        }
        
        public ServiceProducto.Estado ObtenerEstado(string oEstado)
        {
            return base.Channel.ObtenerEstado(oEstado);
        }
        
        public System.Threading.Tasks.Task<ServiceProducto.Estado> ObtenerEstadoAsync(string oEstado)
        {
            return base.Channel.ObtenerEstadoAsync(oEstado);
        }
        
        public ServiceProducto.RubroProducto ObtenerRubroProducto(string oRubroProducto)
        {
            return base.Channel.ObtenerRubroProducto(oRubroProducto);
        }
        
        public System.Threading.Tasks.Task<ServiceProducto.RubroProducto> ObtenerRubroProductoAsync(string oRubroProducto)
        {
            return base.Channel.ObtenerRubroProductoAsync(oRubroProducto);
        }
        
        public ServiceProducto.Marca ObtenerMarca(string oMarca)
        {
            return base.Channel.ObtenerMarca(oMarca);
        }
        
        public System.Threading.Tasks.Task<ServiceProducto.Marca> ObtenerMarcaAsync(string oMarca)
        {
            return base.Channel.ObtenerMarcaAsync(oMarca);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceProducto))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceProducto))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:10524/ServiceProducto.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceProductoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceProducto);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceProductoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceProducto);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceProducto,
        }
    }
}
