//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceProducto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoProducto", Namespace="http://schemas.datacontract.org/2004/07/CapaServicioServidor.DataObjectTransfer")]
    public partial class DtoProducto : object
    {
        
        private string CodigoProductoField;
        
        private double CostoProductoField;
        
        private string DescripcionEstadoField;
        
        private string DescripcionGeneroProductoField;
        
        private string DescripcionMarcaProductoField;
        
        private string DescripcionProductoField;
        
        private string DescripcionRubroProductoField;
        
        private string DescripcionTipoTalleField;
        
        private ServiceProducto.DetalleProducto[] DetallePoductoField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdProductoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoProducto
        {
            get
            {
                return this.CodigoProductoField;
            }
            set
            {
                this.CodigoProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CostoProducto
        {
            get
            {
                return this.CostoProductoField;
            }
            set
            {
                this.CostoProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionEstado
        {
            get
            {
                return this.DescripcionEstadoField;
            }
            set
            {
                this.DescripcionEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionGeneroProducto
        {
            get
            {
                return this.DescripcionGeneroProductoField;
            }
            set
            {
                this.DescripcionGeneroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionMarcaProducto
        {
            get
            {
                return this.DescripcionMarcaProductoField;
            }
            set
            {
                this.DescripcionMarcaProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionProducto
        {
            get
            {
                return this.DescripcionProductoField;
            }
            set
            {
                this.DescripcionProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionRubroProducto
        {
            get
            {
                return this.DescripcionRubroProductoField;
            }
            set
            {
                this.DescripcionRubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionTipoTalle
        {
            get
            {
                return this.DescripcionTipoTalleField;
            }
            set
            {
                this.DescripcionTipoTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.DetalleProducto[] DetallePoducto
        {
            get
            {
                return this.DetallePoductoField;
            }
            set
            {
                this.DetallePoductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto
        {
            get
            {
                return this.IdProductoField;
            }
            set
            {
                this.IdProductoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleProducto", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class DetalleProducto : object
    {
        
        private System.DateTime FechaRegistroField;
        
        private int IdDetalleProductoField;
        
        private int IdProductoField;
        
        private int IdTalleColorField;
        
        private ServiceProducto.Estado OEstadoField;
        
        private int StockField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDetalleProducto
        {
            get
            {
                return this.IdDetalleProductoField;
            }
            set
            {
                this.IdDetalleProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto
        {
            get
            {
                return this.IdProductoField;
            }
            set
            {
                this.IdProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTalleColor
        {
            get
            {
                return this.IdTalleColorField;
            }
            set
            {
                this.IdTalleColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public enum Estado : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactivo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activo = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoFormProducto", Namespace="http://schemas.datacontract.org/2004/07/CapaServicioServidor.DataObjectTransfer.P" +
        "roducto")]
    public partial class DtoFormProducto : object
    {
        
        private string[] ListColorField;
        
        private string[] ListEstadoField;
        
        private string[] ListGeneroProductoField;
        
        private string[] ListMarcaProductoField;
        
        private string[] ListRubroProductoField;
        
        private System.ValueTuple<string, string>[] ListTalleField;
        
        private string[] ListTipoTalleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ListColor
        {
            get
            {
                return this.ListColorField;
            }
            set
            {
                this.ListColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ListEstado
        {
            get
            {
                return this.ListEstadoField;
            }
            set
            {
                this.ListEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ListGeneroProducto
        {
            get
            {
                return this.ListGeneroProductoField;
            }
            set
            {
                this.ListGeneroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ListMarcaProducto
        {
            get
            {
                return this.ListMarcaProductoField;
            }
            set
            {
                this.ListMarcaProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ListRubroProducto
        {
            get
            {
                return this.ListRubroProductoField;
            }
            set
            {
                this.ListRubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.ValueTuple<string, string>[] ListTalle
        {
            get
            {
                return this.ListTalleField;
            }
            set
            {
                this.ListTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ListTipoTalle
        {
            get
            {
                return this.ListTipoTalleField;
            }
            set
            {
                this.ListTipoTalleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProducto.IServiceCrudOf_DtoProducto")]
    public interface IServiceCrudOf_DtoProducto
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoProducto/Registrar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoProducto/RegistrarResponse")]
        bool Registrar(ServiceProducto.DtoProducto oEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoProducto/Registrar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoProducto/RegistrarResponse")]
        System.Threading.Tasks.Task<bool> RegistrarAsync(ServiceProducto.DtoProducto oEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoProducto/Actualizar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoProducto/ActualizarResponse")]
        bool Actualizar(ServiceProducto.DtoProducto oEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoProducto/Actualizar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoProducto/ActualizarResponse")]
        System.Threading.Tasks.Task<bool> ActualizarAsync(ServiceProducto.DtoProducto oEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoProducto/Eliminar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoProducto/EliminarResponse")]
        bool Eliminar(int idEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoProducto/Eliminar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoProducto/EliminarResponse")]
        System.Threading.Tasks.Task<bool> EliminarAsync(int idEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoProducto/Mostrar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoProducto/MostrarResponse")]
        ServiceProducto.DtoProducto[] Mostrar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoProducto/Mostrar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoProducto/MostrarResponse")]
        System.Threading.Tasks.Task<ServiceProducto.DtoProducto[]> MostrarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceCrudOf_DtoProductoChannel : ServiceProducto.IServiceCrudOf_DtoProducto, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceCrudOf_DtoProductoClient : System.ServiceModel.ClientBase<ServiceProducto.IServiceCrudOf_DtoProducto>, ServiceProducto.IServiceCrudOf_DtoProducto
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceCrudOf_DtoProductoClient() : 
                base(ServiceCrudOf_DtoProductoClient.GetDefaultBinding(), ServiceCrudOf_DtoProductoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceCrudOf_DtoProducto.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceCrudOf_DtoProductoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceCrudOf_DtoProductoClient.GetBindingForEndpoint(endpointConfiguration), ServiceCrudOf_DtoProductoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceCrudOf_DtoProductoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceCrudOf_DtoProductoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceCrudOf_DtoProductoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceCrudOf_DtoProductoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceCrudOf_DtoProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool Registrar(ServiceProducto.DtoProducto oEntity)
        {
            return base.Channel.Registrar(oEntity);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarAsync(ServiceProducto.DtoProducto oEntity)
        {
            return base.Channel.RegistrarAsync(oEntity);
        }
        
        public bool Actualizar(ServiceProducto.DtoProducto oEntity)
        {
            return base.Channel.Actualizar(oEntity);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarAsync(ServiceProducto.DtoProducto oEntity)
        {
            return base.Channel.ActualizarAsync(oEntity);
        }
        
        public bool Eliminar(int idEntity)
        {
            return base.Channel.Eliminar(idEntity);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAsync(int idEntity)
        {
            return base.Channel.EliminarAsync(idEntity);
        }
        
        public ServiceProducto.DtoProducto[] Mostrar()
        {
            return base.Channel.Mostrar();
        }
        
        public System.Threading.Tasks.Task<ServiceProducto.DtoProducto[]> MostrarAsync()
        {
            return base.Channel.MostrarAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceCrudOf_DtoProducto))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceCrudOf_DtoProducto))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:10524/ServiceProducto.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceCrudOf_DtoProductoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceCrudOf_DtoProducto);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceCrudOf_DtoProductoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceCrudOf_DtoProducto);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceCrudOf_DtoProducto,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProducto.IFormularioOf_DtoFormProducto")]
    public interface IFormularioOf_DtoFormProducto
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFormularioOf_DtoFormProducto/GetFormulario", ReplyAction="http://tempuri.org/IFormularioOf_DtoFormProducto/GetFormularioResponse")]
        ServiceProducto.DtoFormProducto GetFormulario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFormularioOf_DtoFormProducto/GetFormulario", ReplyAction="http://tempuri.org/IFormularioOf_DtoFormProducto/GetFormularioResponse")]
        System.Threading.Tasks.Task<ServiceProducto.DtoFormProducto> GetFormularioAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IFormularioOf_DtoFormProductoChannel : ServiceProducto.IFormularioOf_DtoFormProducto, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class FormularioOf_DtoFormProductoClient : System.ServiceModel.ClientBase<ServiceProducto.IFormularioOf_DtoFormProducto>, ServiceProducto.IFormularioOf_DtoFormProducto
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FormularioOf_DtoFormProductoClient() : 
                base(FormularioOf_DtoFormProductoClient.GetDefaultBinding(), FormularioOf_DtoFormProductoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IFormularioOf_DtoFormProducto.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FormularioOf_DtoFormProductoClient(EndpointConfiguration endpointConfiguration) : 
                base(FormularioOf_DtoFormProductoClient.GetBindingForEndpoint(endpointConfiguration), FormularioOf_DtoFormProductoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FormularioOf_DtoFormProductoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FormularioOf_DtoFormProductoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FormularioOf_DtoFormProductoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FormularioOf_DtoFormProductoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FormularioOf_DtoFormProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceProducto.DtoFormProducto GetFormulario()
        {
            return base.Channel.GetFormulario();
        }
        
        public System.Threading.Tasks.Task<ServiceProducto.DtoFormProducto> GetFormularioAsync()
        {
            return base.Channel.GetFormularioAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFormularioOf_DtoFormProducto))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFormularioOf_DtoFormProducto))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:10524/ServiceProducto.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FormularioOf_DtoFormProductoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IFormularioOf_DtoFormProducto);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FormularioOf_DtoFormProductoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IFormularioOf_DtoFormProducto);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IFormularioOf_DtoFormProducto,
        }
    }
}
