//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceProducto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoProducto", Namespace="http://schemas.datacontract.org/2004/07/CapaServicioServidor")]
    public partial class DtoProducto : object
    {
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdProductoField;
        
        private ServiceProducto.Estado OEstadoField;
        
        private ServiceProducto.GeneroProducto OGeneroProductoField;
        
        private ServiceProducto.Marca OMarcaField;
        
        private ServiceProducto.ProductoVenta[] OProductoVentaField;
        
        private ServiceProducto.RubroProducto ORubroProductoField;
        
        private ServiceProducto.TipoTalle OTipoTalleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto
        {
            get
            {
                return this.IdProductoField;
            }
            set
            {
                this.IdProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.GeneroProducto OGeneroProducto
        {
            get
            {
                return this.OGeneroProductoField;
            }
            set
            {
                this.OGeneroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Marca OMarca
        {
            get
            {
                return this.OMarcaField;
            }
            set
            {
                this.OMarcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.ProductoVenta[] OProductoVenta
        {
            get
            {
                return this.OProductoVentaField;
            }
            set
            {
                this.OProductoVentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.RubroProducto ORubroProducto
        {
            get
            {
                return this.ORubroProductoField;
            }
            set
            {
                this.ORubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.TipoTalle OTipoTalle
        {
            get
            {
                return this.OTipoTalleField;
            }
            set
            {
                this.OTipoTalleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Marca", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class Marca : object
    {
        
        private string DescripcionField;
        
        private int IdMarcaField;
        
        private ServiceProducto.Estado OEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMarca
        {
            get
            {
                return this.IdMarcaField;
            }
            set
            {
                this.IdMarcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RubroProducto", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class RubroProducto : object
    {
        
        private string CodigoRubroProductoField;
        
        private string DescripcionRubroProductoField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdRubroProductoField;
        
        private double MargenGananciaField;
        
        private ServiceProducto.Estado OEstadoField;
        
        private ServiceProducto.Impuesto OImpuestoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRubroProducto
        {
            get
            {
                return this.CodigoRubroProductoField;
            }
            set
            {
                this.CodigoRubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionRubroProducto
        {
            get
            {
                return this.DescripcionRubroProductoField;
            }
            set
            {
                this.DescripcionRubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRubroProducto
        {
            get
            {
                return this.IdRubroProductoField;
            }
            set
            {
                this.IdRubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MargenGanancia
        {
            get
            {
                return this.MargenGananciaField;
            }
            set
            {
                this.MargenGananciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Impuesto OImpuesto
        {
            get
            {
                return this.OImpuestoField;
            }
            set
            {
                this.OImpuestoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoTalle", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class TipoTalle : object
    {
        
        private string DescripcionField;
        
        private int IdTipoTalleField;
        
        private ServiceProducto.Estado OEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoTalle
        {
            get
            {
                return this.IdTipoTalleField;
            }
            set
            {
                this.IdTipoTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public enum Estado : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactivo = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneroProducto", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public enum GeneroProducto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unisex = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Masculino = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Femenino = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoVenta", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class ProductoVenta : object
    {
        
        private int CantidadField;
        
        private double CostoField;
        
        private ServiceProducto.Color OColorField;
        
        private ServiceProducto.Talle OTalleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Costo
        {
            get
            {
                return this.CostoField;
            }
            set
            {
                this.CostoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Color OColor
        {
            get
            {
                return this.OColorField;
            }
            set
            {
                this.OColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Talle OTalle
        {
            get
            {
                return this.OTalleField;
            }
            set
            {
                this.OTalleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Color", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class Color : object
    {
        
        private string CodigoColorField;
        
        private string DescripcionColorField;
        
        private int IdColorField;
        
        private ServiceProducto.Estado OEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoColor
        {
            get
            {
                return this.CodigoColorField;
            }
            set
            {
                this.CodigoColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionColor
        {
            get
            {
                return this.DescripcionColorField;
            }
            set
            {
                this.DescripcionColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdColor
        {
            get
            {
                return this.IdColorField;
            }
            set
            {
                this.IdColorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Talle", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class Talle : object
    {
        
        private string CodigoTalleField;
        
        private string DescripcionTalleField;
        
        private int IdTalleField;
        
        private ServiceProducto.Estado OEstadoField;
        
        private ServiceProducto.TipoTalle OTipoTalleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTalle
        {
            get
            {
                return this.CodigoTalleField;
            }
            set
            {
                this.CodigoTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionTalle
        {
            get
            {
                return this.DescripcionTalleField;
            }
            set
            {
                this.DescripcionTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTalle
        {
            get
            {
                return this.IdTalleField;
            }
            set
            {
                this.IdTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.TipoTalle OTipoTalle
        {
            get
            {
                return this.OTipoTalleField;
            }
            set
            {
                this.OTipoTalleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Impuesto", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class Impuesto : object
    {
        
        private double AlicuotaField;
        
        private string DescripcionField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdImpuestoField;
        
        private ServiceProducto.Estado OEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Alicuota
        {
            get
            {
                return this.AlicuotaField;
            }
            set
            {
                this.AlicuotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdImpuesto
        {
            get
            {
                return this.IdImpuestoField;
            }
            set
            {
                this.IdImpuestoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class Producto : object
    {
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdProductoField;
        
        private ServiceProducto.Estado OEstadoField;
        
        private ServiceProducto.GeneroProducto OGeneroProductoField;
        
        private ServiceProducto.Marca OMarcaField;
        
        private ServiceProducto.ProductoVenta[] OProductoVentaField;
        
        private ServiceProducto.RubroProducto ORubroProductoField;
        
        private ServiceProducto.TipoTalle OTipoTalleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto
        {
            get
            {
                return this.IdProductoField;
            }
            set
            {
                this.IdProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.GeneroProducto OGeneroProducto
        {
            get
            {
                return this.OGeneroProductoField;
            }
            set
            {
                this.OGeneroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.Marca OMarca
        {
            get
            {
                return this.OMarcaField;
            }
            set
            {
                this.OMarcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.ProductoVenta[] OProductoVenta
        {
            get
            {
                return this.OProductoVentaField;
            }
            set
            {
                this.OProductoVentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.RubroProducto ORubroProducto
        {
            get
            {
                return this.ORubroProductoField;
            }
            set
            {
                this.ORubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProducto.TipoTalle OTipoTalle
        {
            get
            {
                return this.OTipoTalleField;
            }
            set
            {
                this.OTipoTalleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProducto.IServiceProducto")]
    public interface IServiceProducto
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/IngresarProducto", ReplyAction="http://tempuri.org/IServiceProducto/IngresarProductoResponse")]
        bool IngresarProducto(ServiceProducto.DtoProducto oProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/IngresarProducto", ReplyAction="http://tempuri.org/IServiceProducto/IngresarProductoResponse")]
        System.Threading.Tasks.Task<bool> IngresarProductoAsync(ServiceProducto.DtoProducto oProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ModificarProducto", ReplyAction="http://tempuri.org/IServiceProducto/ModificarProductoResponse")]
        bool ModificarProducto(ServiceProducto.DtoProducto oProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ModificarProducto", ReplyAction="http://tempuri.org/IServiceProducto/ModificarProductoResponse")]
        System.Threading.Tasks.Task<bool> ModificarProductoAsync(ServiceProducto.DtoProducto oProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/EliminarProducto", ReplyAction="http://tempuri.org/IServiceProducto/EliminarProductoResponse")]
        bool EliminarProducto(int IdProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/EliminarProducto", ReplyAction="http://tempuri.org/IServiceProducto/EliminarProductoResponse")]
        System.Threading.Tasks.Task<bool> EliminarProductoAsync(int IdProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ListaProducto", ReplyAction="http://tempuri.org/IServiceProducto/ListaProductoResponse")]
        ServiceProducto.DtoProducto[] ListaProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ListaProducto", ReplyAction="http://tempuri.org/IServiceProducto/ListaProductoResponse")]
        System.Threading.Tasks.Task<ServiceProducto.DtoProducto[]> ListaProductoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerGeneroProducto", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerGeneroProductoResponse")]
        ServiceProducto.GeneroProducto ObtenerGeneroProducto(string oGeneroProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerGeneroProducto", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerGeneroProductoResponse")]
        System.Threading.Tasks.Task<ServiceProducto.GeneroProducto> ObtenerGeneroProductoAsync(string oGeneroProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerEstado", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerEstadoResponse")]
        ServiceProducto.Estado ObtenerEstado(string oEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerEstado", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerEstadoResponse")]
        System.Threading.Tasks.Task<ServiceProducto.Estado> ObtenerEstadoAsync(string oEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerRubroProducto", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerRubroProductoResponse")]
        ServiceProducto.RubroProducto ObtenerRubroProducto(string oRubroProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerRubroProducto", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerRubroProductoResponse")]
        System.Threading.Tasks.Task<ServiceProducto.RubroProducto> ObtenerRubroProductoAsync(string oRubroProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerMarca", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerMarcaResponse")]
        ServiceProducto.Marca ObtenerMarca(string oMarca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerMarca", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerMarcaResponse")]
        System.Threading.Tasks.Task<ServiceProducto.Marca> ObtenerMarcaAsync(string oMarca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerColor", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerColorResponse")]
        ServiceProducto.Color ObtenerColor(string oColor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerColor", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerColorResponse")]
        System.Threading.Tasks.Task<ServiceProducto.Color> ObtenerColorAsync(string oColor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerTipoTalle", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerTipoTalleResponse")]
        ServiceProducto.TipoTalle ObtenerTipoTalle(string oTipoTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/ObtenerTipoTalle", ReplyAction="http://tempuri.org/IServiceProducto/ObtenerTipoTalleResponse")]
        System.Threading.Tasks.Task<ServiceProducto.TipoTalle> ObtenerTipoTalleAsync(string oTipoTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/BuscarProductoById", ReplyAction="http://tempuri.org/IServiceProducto/BuscarProductoByIdResponse")]
        ServiceProducto.Producto BuscarProductoById(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/BuscarProductoById", ReplyAction="http://tempuri.org/IServiceProducto/BuscarProductoByIdResponse")]
        System.Threading.Tasks.Task<ServiceProducto.Producto> BuscarProductoByIdAsync(int idProducto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceProductoChannel : ServiceProducto.IServiceProducto, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceProductoClient : System.ServiceModel.ClientBase<ServiceProducto.IServiceProducto>, ServiceProducto.IServiceProducto
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceProductoClient() : 
                base(ServiceProductoClient.GetDefaultBinding(), ServiceProductoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceProducto.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceProductoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceProductoClient.GetBindingForEndpoint(endpointConfiguration), ServiceProductoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceProductoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceProductoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceProductoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceProductoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool IngresarProducto(ServiceProducto.DtoProducto oProducto)
        {
            return base.Channel.IngresarProducto(oProducto);
        }
        
        public System.Threading.Tasks.Task<bool> IngresarProductoAsync(ServiceProducto.DtoProducto oProducto)
        {
            return base.Channel.IngresarProductoAsync(oProducto);
        }
        
        public bool ModificarProducto(ServiceProducto.DtoProducto oProducto)
        {
            return base.Channel.ModificarProducto(oProducto);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarProductoAsync(ServiceProducto.DtoProducto oProducto)
        {
            return base.Channel.ModificarProductoAsync(oProducto);
        }
        
        public bool EliminarProducto(int IdProducto)
        {
            return base.Channel.EliminarProducto(IdProducto);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProductoAsync(int IdProducto)
        {
            return base.Channel.EliminarProductoAsync(IdProducto);
        }
        
        public ServiceProducto.DtoProducto[] ListaProducto()
        {
            return base.Channel.ListaProducto();
        }
        
        public System.Threading.Tasks.Task<ServiceProducto.DtoProducto[]> ListaProductoAsync()
        {
            return base.Channel.ListaProductoAsync();
        }
        
        public ServiceProducto.GeneroProducto ObtenerGeneroProducto(string oGeneroProducto)
        {
            return base.Channel.ObtenerGeneroProducto(oGeneroProducto);
        }
        
        public System.Threading.Tasks.Task<ServiceProducto.GeneroProducto> ObtenerGeneroProductoAsync(string oGeneroProducto)
        {
            return base.Channel.ObtenerGeneroProductoAsync(oGeneroProducto);
        }
        
        public ServiceProducto.Estado ObtenerEstado(string oEstado)
        {
            return base.Channel.ObtenerEstado(oEstado);
        }
        
        public System.Threading.Tasks.Task<ServiceProducto.Estado> ObtenerEstadoAsync(string oEstado)
        {
            return base.Channel.ObtenerEstadoAsync(oEstado);
        }
        
        public ServiceProducto.RubroProducto ObtenerRubroProducto(string oRubroProducto)
        {
            return base.Channel.ObtenerRubroProducto(oRubroProducto);
        }
        
        public System.Threading.Tasks.Task<ServiceProducto.RubroProducto> ObtenerRubroProductoAsync(string oRubroProducto)
        {
            return base.Channel.ObtenerRubroProductoAsync(oRubroProducto);
        }
        
        public ServiceProducto.Marca ObtenerMarca(string oMarca)
        {
            return base.Channel.ObtenerMarca(oMarca);
        }
        
        public System.Threading.Tasks.Task<ServiceProducto.Marca> ObtenerMarcaAsync(string oMarca)
        {
            return base.Channel.ObtenerMarcaAsync(oMarca);
        }
        
        public ServiceProducto.Color ObtenerColor(string oColor)
        {
            return base.Channel.ObtenerColor(oColor);
        }
        
        public System.Threading.Tasks.Task<ServiceProducto.Color> ObtenerColorAsync(string oColor)
        {
            return base.Channel.ObtenerColorAsync(oColor);
        }
        
        public ServiceProducto.TipoTalle ObtenerTipoTalle(string oTipoTalle)
        {
            return base.Channel.ObtenerTipoTalle(oTipoTalle);
        }
        
        public System.Threading.Tasks.Task<ServiceProducto.TipoTalle> ObtenerTipoTalleAsync(string oTipoTalle)
        {
            return base.Channel.ObtenerTipoTalleAsync(oTipoTalle);
        }
        
        public ServiceProducto.Producto BuscarProductoById(int idProducto)
        {
            return base.Channel.BuscarProductoById(idProducto);
        }
        
        public System.Threading.Tasks.Task<ServiceProducto.Producto> BuscarProductoByIdAsync(int idProducto)
        {
            return base.Channel.BuscarProductoByIdAsync(idProducto);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceProducto))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceProducto))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:10524/ServiceProducto.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceProductoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceProducto);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceProductoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceProducto);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceProducto,
        }
    }
}
