//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicePruebaUnitaria
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRespuesta", Namespace="http://schemas.datacontract.org/2004/07/CapaServicioServidor")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicePruebaUnitaria.DtoUsuario))]
    public partial class BaseRespuesta : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoUsuario", Namespace="http://schemas.datacontract.org/2004/07/CapaServicioServidor")]
    public partial class DtoUsuario : ServicePruebaUnitaria.BaseRespuesta
    {
        
        private string ContraseñaField;
        
        private string EmailField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdUsuarioField;
        
        private string NombreUsuarioField;
        
        private ServicePruebaUnitaria.Empleado OEmpleadoField;
        
        private ServicePruebaUnitaria.Estado OEstadoField;
        
        private ServicePruebaUnitaria.Rol ORolField;
        
        private ServicePruebaUnitaria.Tienda OTiendaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña
        {
            get
            {
                return this.ContraseñaField;
            }
            set
            {
                this.ContraseñaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario
        {
            get
            {
                return this.NombreUsuarioField;
            }
            set
            {
                this.NombreUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicePruebaUnitaria.Empleado OEmpleado
        {
            get
            {
                return this.OEmpleadoField;
            }
            set
            {
                this.OEmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicePruebaUnitaria.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicePruebaUnitaria.Rol ORol
        {
            get
            {
                return this.ORolField;
            }
            set
            {
                this.ORolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicePruebaUnitaria.Tienda OTienda
        {
            get
            {
                return this.OTiendaField;
            }
            set
            {
                this.OTiendaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class Empleado : ServicePruebaUnitaria.Persona
    {
        
        private int AntiguedadField;
        
        private string CuilField;
        
        private System.DateTime FechaAltaField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdEmpleadoField;
        
        private ServicePruebaUnitaria.Estado OEstadoField;
        
        private ServicePruebaUnitaria.Persona OPersonaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Antiguedad
        {
            get
            {
                return this.AntiguedadField;
            }
            set
            {
                this.AntiguedadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuil
        {
            get
            {
                return this.CuilField;
            }
            set
            {
                this.CuilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaAlta
        {
            get
            {
                return this.FechaAltaField;
            }
            set
            {
                this.FechaAltaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmpleado
        {
            get
            {
                return this.IdEmpleadoField;
            }
            set
            {
                this.IdEmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicePruebaUnitaria.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicePruebaUnitaria.Persona OPersona
        {
            get
            {
                return this.OPersonaField;
            }
            set
            {
                this.OPersonaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rol", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class Rol : object
    {
        
        private string DescripcionField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdRolField;
        
        private ServicePruebaUnitaria.Estado OEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRol
        {
            get
            {
                return this.IdRolField;
            }
            set
            {
                this.IdRolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicePruebaUnitaria.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tienda", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class Tienda : object
    {
        
        private string CuitTiendaField;
        
        private string DireccionField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdTiendaField;
        
        private ServicePruebaUnitaria.Estado OEstadoField;
        
        private string RazonSocialField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuitTienda
        {
            get
            {
                return this.CuitTiendaField;
            }
            set
            {
                this.CuitTiendaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTienda
        {
            get
            {
                return this.IdTiendaField;
            }
            set
            {
                this.IdTiendaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicePruebaUnitaria.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial
        {
            get
            {
                return this.RazonSocialField;
            }
            set
            {
                this.RazonSocialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public enum Estado : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactivo = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicePruebaUnitaria.Empleado))]
    public partial class Persona : object
    {
        
        private string ApellidosField;
        
        private string DomicilioField;
        
        private int EdadField;
        
        private System.DateTime FechaNacimientoField;
        
        private int IdPersonaField;
        
        private string NombresField;
        
        private string NumeroDocumentoField;
        
        private ServicePruebaUnitaria.Sexo OSexoField;
        
        private string TelefonoField;
        
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos
        {
            get
            {
                return this.ApellidosField;
            }
            set
            {
                this.ApellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domicilio
        {
            get
            {
                return this.DomicilioField;
            }
            set
            {
                this.DomicilioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad
        {
            get
            {
                return this.EdadField;
            }
            set
            {
                this.EdadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPersona
        {
            get
            {
                return this.IdPersonaField;
            }
            set
            {
                this.IdPersonaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento
        {
            get
            {
                return this.NumeroDocumentoField;
            }
            set
            {
                this.NumeroDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicePruebaUnitaria.Sexo OSexo
        {
            get
            {
                return this.OSexoField;
            }
            set
            {
                this.OSexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento
        {
            get
            {
                return this.TipoDocumentoField;
            }
            set
            {
                this.TipoDocumentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sexo", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class Sexo : object
    {
        
        private string DescripcionField;
        
        private int IdSexoField;
        
        private ServicePruebaUnitaria.Estado oEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSexo
        {
            get
            {
                return this.IdSexoField;
            }
            set
            {
                this.IdSexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicePruebaUnitaria.Estado oEstado
        {
            get
            {
                return this.oEstadoField;
            }
            set
            {
                this.oEstadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePruebaUnitaria.IServiceUsuario")]
    public interface IServiceUsuario
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/AgregarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/AgregarUsuarioResponse")]
        bool AgregarUsuario(ServicePruebaUnitaria.DtoUsuario oUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/AgregarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/AgregarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> AgregarUsuarioAsync(ServicePruebaUnitaria.DtoUsuario oUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ModificarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/ModificarUsuarioResponse")]
        bool ModificarUsuario(ServicePruebaUnitaria.DtoUsuario oUsuario, int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ModificarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ModificarUsuarioAsync(ServicePruebaUnitaria.DtoUsuario oUsuario, int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/EliminarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/EliminarUsuarioResponse")]
        bool EliminarUsuario(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/EliminarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/LoginUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/LoginUsuarioResponse")]
        bool LoginUsuario(string usuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/LoginUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/LoginUsuarioResponse")]
        System.Threading.Tasks.Task<bool> LoginUsuarioAsync(string usuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ObtenerUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/ObtenerUsuarioResponse")]
        ServicePruebaUnitaria.DtoUsuario[] ObtenerUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ObtenerUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<ServicePruebaUnitaria.DtoUsuario[]> ObtenerUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ObtenerUsuarioByNombre", ReplyAction="http://tempuri.org/IServiceUsuario/ObtenerUsuarioByNombreResponse")]
        ServicePruebaUnitaria.DtoUsuario ObtenerUsuarioByNombre(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ObtenerUsuarioByNombre", ReplyAction="http://tempuri.org/IServiceUsuario/ObtenerUsuarioByNombreResponse")]
        System.Threading.Tasks.Task<ServicePruebaUnitaria.DtoUsuario> ObtenerUsuarioByNombreAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/RecuperarContraseña", ReplyAction="http://tempuri.org/IServiceUsuario/RecuperarContraseñaResponse")]
        bool RecuperarContraseña(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/RecuperarContraseña", ReplyAction="http://tempuri.org/IServiceUsuario/RecuperarContraseñaResponse")]
        System.Threading.Tasks.Task<bool> RecuperarContraseñaAsync(string usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceUsuarioChannel : ServicePruebaUnitaria.IServiceUsuario, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceUsuarioClient : System.ServiceModel.ClientBase<ServicePruebaUnitaria.IServiceUsuario>, ServicePruebaUnitaria.IServiceUsuario
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceUsuarioClient() : 
                base(ServiceUsuarioClient.GetDefaultBinding(), ServiceUsuarioClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceUsuario.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceUsuarioClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceUsuarioClient.GetBindingForEndpoint(endpointConfiguration), ServiceUsuarioClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceUsuarioClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceUsuarioClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceUsuarioClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceUsuarioClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool AgregarUsuario(ServicePruebaUnitaria.DtoUsuario oUsuario)
        {
            return base.Channel.AgregarUsuario(oUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarUsuarioAsync(ServicePruebaUnitaria.DtoUsuario oUsuario)
        {
            return base.Channel.AgregarUsuarioAsync(oUsuario);
        }
        
        public bool ModificarUsuario(ServicePruebaUnitaria.DtoUsuario oUsuario, int IdUsuario)
        {
            return base.Channel.ModificarUsuario(oUsuario, IdUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarUsuarioAsync(ServicePruebaUnitaria.DtoUsuario oUsuario, int IdUsuario)
        {
            return base.Channel.ModificarUsuarioAsync(oUsuario, IdUsuario);
        }
        
        public bool EliminarUsuario(int IdUsuario)
        {
            return base.Channel.EliminarUsuario(IdUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(int IdUsuario)
        {
            return base.Channel.EliminarUsuarioAsync(IdUsuario);
        }
        
        public bool LoginUsuario(string usuario, string contraseña)
        {
            return base.Channel.LoginUsuario(usuario, contraseña);
        }
        
        public System.Threading.Tasks.Task<bool> LoginUsuarioAsync(string usuario, string contraseña)
        {
            return base.Channel.LoginUsuarioAsync(usuario, contraseña);
        }
        
        public ServicePruebaUnitaria.DtoUsuario[] ObtenerUsuario()
        {
            return base.Channel.ObtenerUsuario();
        }
        
        public System.Threading.Tasks.Task<ServicePruebaUnitaria.DtoUsuario[]> ObtenerUsuarioAsync()
        {
            return base.Channel.ObtenerUsuarioAsync();
        }
        
        public ServicePruebaUnitaria.DtoUsuario ObtenerUsuarioByNombre(string usuario)
        {
            return base.Channel.ObtenerUsuarioByNombre(usuario);
        }
        
        public System.Threading.Tasks.Task<ServicePruebaUnitaria.DtoUsuario> ObtenerUsuarioByNombreAsync(string usuario)
        {
            return base.Channel.ObtenerUsuarioByNombreAsync(usuario);
        }
        
        public bool RecuperarContraseña(string usuario)
        {
            return base.Channel.RecuperarContraseña(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> RecuperarContraseñaAsync(string usuario)
        {
            return base.Channel.RecuperarContraseñaAsync(usuario);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceUsuario))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceUsuario))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:10524/ServiceUsuario.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceUsuarioClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceUsuario);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceUsuarioClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceUsuario);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceUsuario,
        }
    }
}
