//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTipoTalle
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoTalle", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class TipoTalle : object
    {
        
        private string DescripcionTipoTalleField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdTipoTalleField;
        
        private ServiceTipoTalle.Estado OEstadoField;
        
        private ServiceTipoTalle.GeneroProducto OGeneroProductoField;
        
        private ServiceTipoTalle.RubroProducto ORubroProductoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionTipoTalle
        {
            get
            {
                return this.DescripcionTipoTalleField;
            }
            set
            {
                this.DescripcionTipoTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoTalle
        {
            get
            {
                return this.IdTipoTalleField;
            }
            set
            {
                this.IdTipoTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTipoTalle.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTipoTalle.GeneroProducto OGeneroProducto
        {
            get
            {
                return this.OGeneroProductoField;
            }
            set
            {
                this.OGeneroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTipoTalle.RubroProducto ORubroProducto
        {
            get
            {
                return this.ORubroProductoField;
            }
            set
            {
                this.ORubroProductoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneroProducto", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class GeneroProducto : object
    {
        
        private string DescripcionGeneroProductoField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdGeneroProductoField;
        
        private ServiceTipoTalle.Estado OEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionGeneroProducto
        {
            get
            {
                return this.DescripcionGeneroProductoField;
            }
            set
            {
                this.DescripcionGeneroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGeneroProducto
        {
            get
            {
                return this.IdGeneroProductoField;
            }
            set
            {
                this.IdGeneroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTipoTalle.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RubroProducto", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class RubroProducto : object
    {
        
        private string CodigoRubroProductoField;
        
        private string DescripcionRubroProductoField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdRubroProductoField;
        
        private double MargenGananciaField;
        
        private ServiceTipoTalle.Estado OEstadoField;
        
        private ServiceTipoTalle.Impuesto OImpuestoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRubroProducto
        {
            get
            {
                return this.CodigoRubroProductoField;
            }
            set
            {
                this.CodigoRubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionRubroProducto
        {
            get
            {
                return this.DescripcionRubroProductoField;
            }
            set
            {
                this.DescripcionRubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRubroProducto
        {
            get
            {
                return this.IdRubroProductoField;
            }
            set
            {
                this.IdRubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MargenGanancia
        {
            get
            {
                return this.MargenGananciaField;
            }
            set
            {
                this.MargenGananciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTipoTalle.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTipoTalle.Impuesto OImpuesto
        {
            get
            {
                return this.OImpuestoField;
            }
            set
            {
                this.OImpuestoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public enum Estado : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactivo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activo = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Impuesto", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class Impuesto : object
    {
        
        private double AlicuotaField;
        
        private string DescripcionField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdImpuestoField;
        
        private ServiceTipoTalle.Estado OEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Alicuota
        {
            get
            {
                return this.AlicuotaField;
            }
            set
            {
                this.AlicuotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdImpuesto
        {
            get
            {
                return this.IdImpuestoField;
            }
            set
            {
                this.IdImpuestoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTipoTalle.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoTipoTalle", Namespace="http://schemas.datacontract.org/2004/07/CapaServicioServidor")]
    public partial class DtoTipoTalle : object
    {
        
        private string DescripcionTipoTalleField;
        
        private int IdTipoTalleField;
        
        private ServiceTipoTalle.Estado OEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionTipoTalle
        {
            get
            {
                return this.DescripcionTipoTalleField;
            }
            set
            {
                this.DescripcionTipoTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoTalle
        {
            get
            {
                return this.IdTipoTalleField;
            }
            set
            {
                this.IdTipoTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTipoTalle.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTipoTalle.IServiceTipoTalle")]
    public interface IServiceTipoTalle
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoTalle/AgregarTipoTalle", ReplyAction="http://tempuri.org/IServiceTipoTalle/AgregarTipoTalleResponse")]
        bool AgregarTipoTalle(ServiceTipoTalle.TipoTalle oTipoTipoTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoTalle/AgregarTipoTalle", ReplyAction="http://tempuri.org/IServiceTipoTalle/AgregarTipoTalleResponse")]
        System.Threading.Tasks.Task<bool> AgregarTipoTalleAsync(ServiceTipoTalle.TipoTalle oTipoTipoTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoTalle/ModificarTipoTalle", ReplyAction="http://tempuri.org/IServiceTipoTalle/ModificarTipoTalleResponse")]
        bool ModificarTipoTalle(ServiceTipoTalle.TipoTalle oTipoTalle, int IdTipoTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoTalle/ModificarTipoTalle", ReplyAction="http://tempuri.org/IServiceTipoTalle/ModificarTipoTalleResponse")]
        System.Threading.Tasks.Task<bool> ModificarTipoTalleAsync(ServiceTipoTalle.TipoTalle oTipoTalle, int IdTipoTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoTalle/EliminarTipoTalle", ReplyAction="http://tempuri.org/IServiceTipoTalle/EliminarTipoTalleResponse")]
        bool EliminarTipoTalle(int IdTipoTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoTalle/EliminarTipoTalle", ReplyAction="http://tempuri.org/IServiceTipoTalle/EliminarTipoTalleResponse")]
        System.Threading.Tasks.Task<bool> EliminarTipoTalleAsync(int IdTipoTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoTalle/ListaTipoTalle", ReplyAction="http://tempuri.org/IServiceTipoTalle/ListaTipoTalleResponse")]
        ServiceTipoTalle.DtoTipoTalle[] ListaTipoTalle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoTalle/ListaTipoTalle", ReplyAction="http://tempuri.org/IServiceTipoTalle/ListaTipoTalleResponse")]
        System.Threading.Tasks.Task<ServiceTipoTalle.DtoTipoTalle[]> ListaTipoTalleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoTalle/ObtenerTipoTalleByDescripcion", ReplyAction="http://tempuri.org/IServiceTipoTalle/ObtenerTipoTalleByDescripcionResponse")]
        ServiceTipoTalle.TipoTalle ObtenerTipoTalleByDescripcion(string oTipoTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTipoTalle/ObtenerTipoTalleByDescripcion", ReplyAction="http://tempuri.org/IServiceTipoTalle/ObtenerTipoTalleByDescripcionResponse")]
        System.Threading.Tasks.Task<ServiceTipoTalle.TipoTalle> ObtenerTipoTalleByDescripcionAsync(string oTipoTalle);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceTipoTalleChannel : ServiceTipoTalle.IServiceTipoTalle, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceTipoTalleClient : System.ServiceModel.ClientBase<ServiceTipoTalle.IServiceTipoTalle>, ServiceTipoTalle.IServiceTipoTalle
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceTipoTalleClient() : 
                base(ServiceTipoTalleClient.GetDefaultBinding(), ServiceTipoTalleClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceTipoTalle.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTipoTalleClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceTipoTalleClient.GetBindingForEndpoint(endpointConfiguration), ServiceTipoTalleClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTipoTalleClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceTipoTalleClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTipoTalleClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceTipoTalleClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTipoTalleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool AgregarTipoTalle(ServiceTipoTalle.TipoTalle oTipoTipoTalle)
        {
            return base.Channel.AgregarTipoTalle(oTipoTipoTalle);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarTipoTalleAsync(ServiceTipoTalle.TipoTalle oTipoTipoTalle)
        {
            return base.Channel.AgregarTipoTalleAsync(oTipoTipoTalle);
        }
        
        public bool ModificarTipoTalle(ServiceTipoTalle.TipoTalle oTipoTalle, int IdTipoTalle)
        {
            return base.Channel.ModificarTipoTalle(oTipoTalle, IdTipoTalle);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarTipoTalleAsync(ServiceTipoTalle.TipoTalle oTipoTalle, int IdTipoTalle)
        {
            return base.Channel.ModificarTipoTalleAsync(oTipoTalle, IdTipoTalle);
        }
        
        public bool EliminarTipoTalle(int IdTipoTalle)
        {
            return base.Channel.EliminarTipoTalle(IdTipoTalle);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarTipoTalleAsync(int IdTipoTalle)
        {
            return base.Channel.EliminarTipoTalleAsync(IdTipoTalle);
        }
        
        public ServiceTipoTalle.DtoTipoTalle[] ListaTipoTalle()
        {
            return base.Channel.ListaTipoTalle();
        }
        
        public System.Threading.Tasks.Task<ServiceTipoTalle.DtoTipoTalle[]> ListaTipoTalleAsync()
        {
            return base.Channel.ListaTipoTalleAsync();
        }
        
        public ServiceTipoTalle.TipoTalle ObtenerTipoTalleByDescripcion(string oTipoTalle)
        {
            return base.Channel.ObtenerTipoTalleByDescripcion(oTipoTalle);
        }
        
        public System.Threading.Tasks.Task<ServiceTipoTalle.TipoTalle> ObtenerTipoTalleByDescripcionAsync(string oTipoTalle)
        {
            return base.Channel.ObtenerTipoTalleByDescripcionAsync(oTipoTalle);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceTipoTalle))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceTipoTalle))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:10524/ServiceTipoTalle.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceTipoTalleClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceTipoTalle);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceTipoTalleClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceTipoTalle);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceTipoTalle,
        }
    }
}
