//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMarca
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoMarca", Namespace="http://schemas.datacontract.org/2004/07/CapaServicioServidor")]
    public partial class DtoMarca : object
    {
        
        private string DescripcionMarcaProductoField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdMarcaProductoField;
        
        private ServiceMarca.Estado OEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionMarcaProducto
        {
            get
            {
                return this.DescripcionMarcaProductoField;
            }
            set
            {
                this.DescripcionMarcaProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMarcaProducto
        {
            get
            {
                return this.IdMarcaProductoField;
            }
            set
            {
                this.IdMarcaProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceMarca.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public enum Estado : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactivo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activo = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMarca.IServiceCrudOf_DtoMarca")]
    public interface IServiceCrudOf_DtoMarca
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoMarca/Registrar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoMarca/RegistrarResponse")]
        bool Registrar(ServiceMarca.DtoMarca oEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoMarca/Registrar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoMarca/RegistrarResponse")]
        System.Threading.Tasks.Task<bool> RegistrarAsync(ServiceMarca.DtoMarca oEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoMarca/Actualizar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoMarca/ActualizarResponse")]
        bool Actualizar(ServiceMarca.DtoMarca oEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoMarca/Actualizar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoMarca/ActualizarResponse")]
        System.Threading.Tasks.Task<bool> ActualizarAsync(ServiceMarca.DtoMarca oEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoMarca/Eliminar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoMarca/EliminarResponse")]
        bool Eliminar(int idEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoMarca/Eliminar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoMarca/EliminarResponse")]
        System.Threading.Tasks.Task<bool> EliminarAsync(int idEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoMarca/Mostrar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoMarca/MostrarResponse")]
        ServiceMarca.DtoMarca[] Mostrar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCrudOf_DtoMarca/Mostrar", ReplyAction="http://tempuri.org/IServiceCrudOf_DtoMarca/MostrarResponse")]
        System.Threading.Tasks.Task<ServiceMarca.DtoMarca[]> MostrarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceCrudOf_DtoMarcaChannel : ServiceMarca.IServiceCrudOf_DtoMarca, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceCrudOf_DtoMarcaClient : System.ServiceModel.ClientBase<ServiceMarca.IServiceCrudOf_DtoMarca>, ServiceMarca.IServiceCrudOf_DtoMarca
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceCrudOf_DtoMarcaClient() : 
                base(ServiceCrudOf_DtoMarcaClient.GetDefaultBinding(), ServiceCrudOf_DtoMarcaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceCrudOf_DtoMarca.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceCrudOf_DtoMarcaClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceCrudOf_DtoMarcaClient.GetBindingForEndpoint(endpointConfiguration), ServiceCrudOf_DtoMarcaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceCrudOf_DtoMarcaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceCrudOf_DtoMarcaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceCrudOf_DtoMarcaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceCrudOf_DtoMarcaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceCrudOf_DtoMarcaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool Registrar(ServiceMarca.DtoMarca oEntity)
        {
            return base.Channel.Registrar(oEntity);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarAsync(ServiceMarca.DtoMarca oEntity)
        {
            return base.Channel.RegistrarAsync(oEntity);
        }
        
        public bool Actualizar(ServiceMarca.DtoMarca oEntity)
        {
            return base.Channel.Actualizar(oEntity);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarAsync(ServiceMarca.DtoMarca oEntity)
        {
            return base.Channel.ActualizarAsync(oEntity);
        }
        
        public bool Eliminar(int idEntity)
        {
            return base.Channel.Eliminar(idEntity);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAsync(int idEntity)
        {
            return base.Channel.EliminarAsync(idEntity);
        }
        
        public ServiceMarca.DtoMarca[] Mostrar()
        {
            return base.Channel.Mostrar();
        }
        
        public System.Threading.Tasks.Task<ServiceMarca.DtoMarca[]> MostrarAsync()
        {
            return base.Channel.MostrarAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceCrudOf_DtoMarca))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceCrudOf_DtoMarca))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:10524/ServiceMarca.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceCrudOf_DtoMarcaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceCrudOf_DtoMarca);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceCrudOf_DtoMarcaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceCrudOf_DtoMarca);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceCrudOf_DtoMarca,
        }
    }
}
