//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTalle
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Talle", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class Talle : object
    {
        
        private string CodigoTalleField;
        
        private string DescripcionTalleField;
        
        private int IdTalleField;
        
        private ServiceTalle.Estado OEstadoField;
        
        private ServiceTalle.TipoTalle OTipoTalleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTalle
        {
            get
            {
                return this.CodigoTalleField;
            }
            set
            {
                this.CodigoTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionTalle
        {
            get
            {
                return this.DescripcionTalleField;
            }
            set
            {
                this.DescripcionTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTalle
        {
            get
            {
                return this.IdTalleField;
            }
            set
            {
                this.IdTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.TipoTalle OTipoTalle
        {
            get
            {
                return this.OTipoTalleField;
            }
            set
            {
                this.OTipoTalleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoTalle", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class TipoTalle : object
    {
        
        private string DescripcionField;
        
        private int IdTipoTalleField;
        
        private ServiceTalle.Estado OEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoTalle
        {
            get
            {
                return this.IdTipoTalleField;
            }
            set
            {
                this.IdTipoTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public enum Estado : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactivo = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoTalle", Namespace="http://schemas.datacontract.org/2004/07/CapaServicioServidor")]
    public partial class DtoTalle : object
    {
        
        private string CodigoTalleField;
        
        private string DescripcionTalleField;
        
        private int IdTalleField;
        
        private ServiceTalle.Estado OEstadoField;
        
        private ServiceTalle.TipoTalle OTipoTalleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTalle
        {
            get
            {
                return this.CodigoTalleField;
            }
            set
            {
                this.CodigoTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionTalle
        {
            get
            {
                return this.DescripcionTalleField;
            }
            set
            {
                this.DescripcionTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTalle
        {
            get
            {
                return this.IdTalleField;
            }
            set
            {
                this.IdTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.TipoTalle OTipoTalle
        {
            get
            {
                return this.OTipoTalleField;
            }
            set
            {
                this.OTipoTalleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTalle.IServiceTalle")]
    public interface IServiceTalle
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/AgregarTalle", ReplyAction="http://tempuri.org/IServiceTalle/AgregarTalleResponse")]
        bool AgregarTalle(ServiceTalle.Talle oTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/AgregarTalle", ReplyAction="http://tempuri.org/IServiceTalle/AgregarTalleResponse")]
        System.Threading.Tasks.Task<bool> AgregarTalleAsync(ServiceTalle.Talle oTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/ModificarTalle", ReplyAction="http://tempuri.org/IServiceTalle/ModificarTalleResponse")]
        bool ModificarTalle(ServiceTalle.Talle oTalle, int IdTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/ModificarTalle", ReplyAction="http://tempuri.org/IServiceTalle/ModificarTalleResponse")]
        System.Threading.Tasks.Task<bool> ModificarTalleAsync(ServiceTalle.Talle oTalle, int IdTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/EliminarTalle", ReplyAction="http://tempuri.org/IServiceTalle/EliminarTalleResponse")]
        bool EliminarTalle(int IdTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/EliminarTalle", ReplyAction="http://tempuri.org/IServiceTalle/EliminarTalleResponse")]
        System.Threading.Tasks.Task<bool> EliminarTalleAsync(int IdTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/ListaTalle", ReplyAction="http://tempuri.org/IServiceTalle/ListaTalleResponse")]
        ServiceTalle.DtoTalle[] ListaTalle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/ListaTalle", ReplyAction="http://tempuri.org/IServiceTalle/ListaTalleResponse")]
        System.Threading.Tasks.Task<ServiceTalle.DtoTalle[]> ListaTalleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/ObtenerTalle", ReplyAction="http://tempuri.org/IServiceTalle/ObtenerTalleResponse")]
        ServiceTalle.Talle ObtenerTalle(string Rubro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/ObtenerTalle", ReplyAction="http://tempuri.org/IServiceTalle/ObtenerTalleResponse")]
        System.Threading.Tasks.Task<ServiceTalle.Talle> ObtenerTalleAsync(string Rubro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceTalleChannel : ServiceTalle.IServiceTalle, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceTalleClient : System.ServiceModel.ClientBase<ServiceTalle.IServiceTalle>, ServiceTalle.IServiceTalle
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceTalleClient() : 
                base(ServiceTalleClient.GetDefaultBinding(), ServiceTalleClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceTalle.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTalleClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceTalleClient.GetBindingForEndpoint(endpointConfiguration), ServiceTalleClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTalleClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceTalleClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTalleClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceTalleClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTalleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool AgregarTalle(ServiceTalle.Talle oTalle)
        {
            return base.Channel.AgregarTalle(oTalle);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarTalleAsync(ServiceTalle.Talle oTalle)
        {
            return base.Channel.AgregarTalleAsync(oTalle);
        }
        
        public bool ModificarTalle(ServiceTalle.Talle oTalle, int IdTalle)
        {
            return base.Channel.ModificarTalle(oTalle, IdTalle);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarTalleAsync(ServiceTalle.Talle oTalle, int IdTalle)
        {
            return base.Channel.ModificarTalleAsync(oTalle, IdTalle);
        }
        
        public bool EliminarTalle(int IdTalle)
        {
            return base.Channel.EliminarTalle(IdTalle);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarTalleAsync(int IdTalle)
        {
            return base.Channel.EliminarTalleAsync(IdTalle);
        }
        
        public ServiceTalle.DtoTalle[] ListaTalle()
        {
            return base.Channel.ListaTalle();
        }
        
        public System.Threading.Tasks.Task<ServiceTalle.DtoTalle[]> ListaTalleAsync()
        {
            return base.Channel.ListaTalleAsync();
        }
        
        public ServiceTalle.Talle ObtenerTalle(string Rubro)
        {
            return base.Channel.ObtenerTalle(Rubro);
        }
        
        public System.Threading.Tasks.Task<ServiceTalle.Talle> ObtenerTalleAsync(string Rubro)
        {
            return base.Channel.ObtenerTalleAsync(Rubro);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceTalle))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceTalle))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:10524/ServiceTalle.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceTalleClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceTalle);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceTalleClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceTalle);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceTalle,
        }
    }
}
