//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTalle
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Talle", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class Talle : object
    {
        
        private string DescripcionTalleField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdTalleField;
        
        private ServiceTalle.Estado OEstadoField;
        
        private ServiceTalle.GeneroProducto OGeneroProductoField;
        
        private ServiceTalle.RubroProducto ORubroProductoField;
        
        private ServiceTalle.TipoTalle OTipoTalleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionTalle
        {
            get
            {
                return this.DescripcionTalleField;
            }
            set
            {
                this.DescripcionTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTalle
        {
            get
            {
                return this.IdTalleField;
            }
            set
            {
                this.IdTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.GeneroProducto OGeneroProducto
        {
            get
            {
                return this.OGeneroProductoField;
            }
            set
            {
                this.OGeneroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.RubroProducto ORubroProducto
        {
            get
            {
                return this.ORubroProductoField;
            }
            set
            {
                this.ORubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.TipoTalle OTipoTalle
        {
            get
            {
                return this.OTipoTalleField;
            }
            set
            {
                this.OTipoTalleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneroProducto", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class GeneroProducto : object
    {
        
        private string DescripcionGeneroProductoField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdGeneroProductoField;
        
        private ServiceTalle.Estado OEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionGeneroProducto
        {
            get
            {
                return this.DescripcionGeneroProductoField;
            }
            set
            {
                this.DescripcionGeneroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGeneroProducto
        {
            get
            {
                return this.IdGeneroProductoField;
            }
            set
            {
                this.IdGeneroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RubroProducto", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class RubroProducto : object
    {
        
        private string CodigoRubroProductoField;
        
        private string DescripcionRubroProductoField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdRubroProductoField;
        
        private double MargenGananciaField;
        
        private ServiceTalle.Estado OEstadoField;
        
        private ServiceTalle.Impuesto OImpuestoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoRubroProducto
        {
            get
            {
                return this.CodigoRubroProductoField;
            }
            set
            {
                this.CodigoRubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionRubroProducto
        {
            get
            {
                return this.DescripcionRubroProductoField;
            }
            set
            {
                this.DescripcionRubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRubroProducto
        {
            get
            {
                return this.IdRubroProductoField;
            }
            set
            {
                this.IdRubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MargenGanancia
        {
            get
            {
                return this.MargenGananciaField;
            }
            set
            {
                this.MargenGananciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.Impuesto OImpuesto
        {
            get
            {
                return this.OImpuestoField;
            }
            set
            {
                this.OImpuestoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoTalle", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class TipoTalle : object
    {
        
        private string DescripcionTipoTalleField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdTipoTalleField;
        
        private ServiceTalle.Estado OEstadoField;
        
        private ServiceTalle.GeneroProducto OGeneroProductoField;
        
        private ServiceTalle.RubroProducto ORubroProductoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionTipoTalle
        {
            get
            {
                return this.DescripcionTipoTalleField;
            }
            set
            {
                this.DescripcionTipoTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoTalle
        {
            get
            {
                return this.IdTipoTalleField;
            }
            set
            {
                this.IdTipoTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.GeneroProducto OGeneroProducto
        {
            get
            {
                return this.OGeneroProductoField;
            }
            set
            {
                this.OGeneroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.RubroProducto ORubroProducto
        {
            get
            {
                return this.ORubroProductoField;
            }
            set
            {
                this.ORubroProductoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public enum Estado : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactivo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activo = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Impuesto", Namespace="http://schemas.datacontract.org/2004/07/CapaNegocio")]
    public partial class Impuesto : object
    {
        
        private double AlicuotaField;
        
        private string DescripcionField;
        
        private System.DateTime FechaRegistroField;
        
        private int IdImpuestoField;
        
        private ServiceTalle.Estado OEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Alicuota
        {
            get
            {
                return this.AlicuotaField;
            }
            set
            {
                this.AlicuotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro
        {
            get
            {
                return this.FechaRegistroField;
            }
            set
            {
                this.FechaRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdImpuesto
        {
            get
            {
                return this.IdImpuestoField;
            }
            set
            {
                this.IdImpuestoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoTalle", Namespace="http://schemas.datacontract.org/2004/07/CapaServicioServidor")]
    public partial class DtoTalle : object
    {
        
        private string DescripcionTalleField;
        
        private int IdTalleField;
        
        private ServiceTalle.Estado OEstadoField;
        
        private ServiceTalle.GeneroProducto OGeneroProductoField;
        
        private ServiceTalle.RubroProducto ORubroProductoField;
        
        private ServiceTalle.TipoTalle OTipoTalleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionTalle
        {
            get
            {
                return this.DescripcionTalleField;
            }
            set
            {
                this.DescripcionTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTalle
        {
            get
            {
                return this.IdTalleField;
            }
            set
            {
                this.IdTalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.Estado OEstado
        {
            get
            {
                return this.OEstadoField;
            }
            set
            {
                this.OEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.GeneroProducto OGeneroProducto
        {
            get
            {
                return this.OGeneroProductoField;
            }
            set
            {
                this.OGeneroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.RubroProducto ORubroProducto
        {
            get
            {
                return this.ORubroProductoField;
            }
            set
            {
                this.ORubroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceTalle.TipoTalle OTipoTalle
        {
            get
            {
                return this.OTipoTalleField;
            }
            set
            {
                this.OTipoTalleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTalle.IServiceTalle")]
    public interface IServiceTalle
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/AgregarTalle", ReplyAction="http://tempuri.org/IServiceTalle/AgregarTalleResponse")]
        bool AgregarTalle(ServiceTalle.Talle oTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/AgregarTalle", ReplyAction="http://tempuri.org/IServiceTalle/AgregarTalleResponse")]
        System.Threading.Tasks.Task<bool> AgregarTalleAsync(ServiceTalle.Talle oTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/ModificarTalle", ReplyAction="http://tempuri.org/IServiceTalle/ModificarTalleResponse")]
        bool ModificarTalle(ServiceTalle.Talle oTalle, int IdTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/ModificarTalle", ReplyAction="http://tempuri.org/IServiceTalle/ModificarTalleResponse")]
        System.Threading.Tasks.Task<bool> ModificarTalleAsync(ServiceTalle.Talle oTalle, int IdTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/EliminarTalle", ReplyAction="http://tempuri.org/IServiceTalle/EliminarTalleResponse")]
        bool EliminarTalle(int IdTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/EliminarTalle", ReplyAction="http://tempuri.org/IServiceTalle/EliminarTalleResponse")]
        System.Threading.Tasks.Task<bool> EliminarTalleAsync(int IdTalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/ListaTalle", ReplyAction="http://tempuri.org/IServiceTalle/ListaTalleResponse")]
        ServiceTalle.DtoTalle[] ListaTalle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/ListaTalle", ReplyAction="http://tempuri.org/IServiceTalle/ListaTalleResponse")]
        System.Threading.Tasks.Task<ServiceTalle.DtoTalle[]> ListaTalleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/ObtenerTalle", ReplyAction="http://tempuri.org/IServiceTalle/ObtenerTalleResponse")]
        ServiceTalle.Talle ObtenerTalle(string Rubro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTalle/ObtenerTalle", ReplyAction="http://tempuri.org/IServiceTalle/ObtenerTalleResponse")]
        System.Threading.Tasks.Task<ServiceTalle.Talle> ObtenerTalleAsync(string Rubro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceTalleChannel : ServiceTalle.IServiceTalle, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceTalleClient : System.ServiceModel.ClientBase<ServiceTalle.IServiceTalle>, ServiceTalle.IServiceTalle
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceTalleClient() : 
                base(ServiceTalleClient.GetDefaultBinding(), ServiceTalleClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceTalle.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTalleClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceTalleClient.GetBindingForEndpoint(endpointConfiguration), ServiceTalleClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTalleClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceTalleClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTalleClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceTalleClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTalleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool AgregarTalle(ServiceTalle.Talle oTalle)
        {
            return base.Channel.AgregarTalle(oTalle);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarTalleAsync(ServiceTalle.Talle oTalle)
        {
            return base.Channel.AgregarTalleAsync(oTalle);
        }
        
        public bool ModificarTalle(ServiceTalle.Talle oTalle, int IdTalle)
        {
            return base.Channel.ModificarTalle(oTalle, IdTalle);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarTalleAsync(ServiceTalle.Talle oTalle, int IdTalle)
        {
            return base.Channel.ModificarTalleAsync(oTalle, IdTalle);
        }
        
        public bool EliminarTalle(int IdTalle)
        {
            return base.Channel.EliminarTalle(IdTalle);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarTalleAsync(int IdTalle)
        {
            return base.Channel.EliminarTalleAsync(IdTalle);
        }
        
        public ServiceTalle.DtoTalle[] ListaTalle()
        {
            return base.Channel.ListaTalle();
        }
        
        public System.Threading.Tasks.Task<ServiceTalle.DtoTalle[]> ListaTalleAsync()
        {
            return base.Channel.ListaTalleAsync();
        }
        
        public ServiceTalle.Talle ObtenerTalle(string Rubro)
        {
            return base.Channel.ObtenerTalle(Rubro);
        }
        
        public System.Threading.Tasks.Task<ServiceTalle.Talle> ObtenerTalleAsync(string Rubro)
        {
            return base.Channel.ObtenerTalleAsync(Rubro);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceTalle))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceTalle))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:10524/ServiceTalle.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceTalleClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceTalle);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceTalleClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceTalle);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceTalle,
        }
    }
}
